version: '3'
services:
    kafka-producer:
        container_name: kafka-producer
        build:
            context: .
            dockerfile: Dockerfile.producer
        image: kafka-producer:latest
        networks:
            - kafka-network
        expose:
            - 8085
        ports:
            - 8085:8085
        logging:
            driver: json-file

    kafka-consumer:
        container_name: kafka-consumer
        build:
            context: .
            dockerfile: Dockerfile.consumer
        image: kafka-consumer:latest
        networks:
            - kafka-network
        logging:
            driver: json-file

    zookeeper:
        container_name: zookeeper
        image: confluentinc/cp-zookeeper
        networks:
            - kafka-network
        ports:
            - 2181:2181
        environment:
            - ZOOKEEPER_CLIENT_PORT=2181

    kafka:
        image: confluentinc/cp-kafka
        container_name: kafka
        networks:
            - kafka-network
        ports:
            - 9092:9092
        depends_on:
            - zookeeper
        environment:
            - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
            - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
            - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092


networks:
    kafka-network:
        driver: bridge